[phases.pixlet]
dependsOn = ["setup"]
nixPkgs = ["curl"]
cmds = [
  "curl -LO https://github.com/tidbyt/pixlet/releases/download/v0.22.4/pixlet_0.22.4_linux_amd64.tar.gz",
  "tar -xvf pixlet_0.22.4_linux_amd64.tar.gz",
  "chmod +x ./pixlet",
  "sudo mv pixlet /usr/local/bin/pixlet",
]
paths = ["/usr/local/bin"]

[phases.install]
dependsOn = ["pixlet", "..."]
